### ISSUE TITLE
Guessing the artist is case sensitive while guessing the song name is not

### ISSUE THREAD

**Issue by qnxt** [inix1257/osuMusicQuizBot#1]
![2022-08-14_21-12](https://user-images.githubusercontent.com/5400432/184547870-de0a466c-1b96-406e-8b8f-73a84be12422.png)

Guessing the artist is case sensitive while guessing the song name is not.
Both should be the same way I think, preferably being case insensitive.

**Comment by inix1257** [comment]
should be fixed now
